DECLARE
  u_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO u_count
    FROM dba_users t
   WHERE t.username = 'CSOMAG_FUTARSZOLGALAT';
  IF u_count = 1
  THEN
    EXECUTE IMMEDIATE 'drop user CSOMAG_FUTARSZOLGALAT cascade';
  END IF;
END;

CREATE USER CSOMAG_FUTARSZOLGALAT
IDENTIFIED BY futarJelszo 
DEFAULT TABLESPACE users 
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION TO CSOMAG_FUTARSZOLGALAT;
GRANT CREATE PROCEDURE TO CSOMAG_FUTARSZOLGALAT;
GRANT CREATE TABLE TO CSOMAG_FUTARSZOLGALAT;
GRANT CREATE VIEW TO CSOMAG_FUTARSZOLGALAT;
GRANT CREATE SEQUENCE TO CSOMAG_FUTARSZOLGALAT;
GRANT CREATE TRIGGER TO CSOMAG_FUTARSZOLGALAT;
GRANT CREATE TYPE TO CSOMAG_FUTARSZOLGALAT;
